require 'os'

desc 'add all the submodules'
task :init do

    git_bundles = [ 
        "http://github.com/flazz/vim-colorschemes.git",
        "http://github.com/scrooloose/nerdcommenter",
        "http://github.com/scrooloose/nerdtree.git",
        "http://github.com/tpope/vim-cucumber.git",
        "http://github.com/tpope/vim-fugitive.git",
        # "http://github.com/tpope/vim-git.git",
        # "http://github.com/astashov/vim-ruby-debugger.git",
        # "http://github.com/ervandew/supertab.git",
        # "https://github.com/tpope/vim-sensible.git",
        # "http://github.com/godlygeek/tabular.git",
        # "http://github.com/hallison/vim-rdoc.git",
        # "http://github.com/msanders/snipmate.vim.git",
        # "http://github.com/pangloss/vim-javascript.git",
        # "http://github.com/timcharper/textile.vim.git",
        # "http://github.com/tpope/vim-haml.git",
        # "http://github.com/tpope/vim-markdown.git",
        # "http://github.com/tpope/vim-rails.git",
        # "http://github.com/tpope/vim-repeat.git",
        # "http://github.com/tpope/vim-surround.git",
        # "http://github.com/tpope/vim-vividchalk.git",
        # "http://github.com/tsaleh/taskpaper.vim.git",
        # "http://github.com/tsaleh/vim-matchit.git",
        # "http://github.com/tsaleh/vim-shoulda.git",
        # "http://github.com/tsaleh/vim-tmux.git",
        # "http://github.com/vim-ruby/vim-ruby.git",
        # "http://github.com/vim-scripts/Gist.vim.git",
    ]

    git_bundles.each do |url|
        dir = url.split('/').last.sub(/\.git$/, '')
        system "git submodule add #{url} bundle/#{dir}"
    end
end

desc "install"
task :install do
  `git submodule init`
  `git submodule update`
  install_windows if OS.windows?
  install_mac if OS.mac?
end

namespace :install do
    desc 'quickly install windows'
    task :win do
       install_windows
    end
end

require 'fileutils'

def install_windows()
    FileUtils.cp 'vimrc', '../.vimrc' 
    File.open('../.vimrc', 'a') { |file| 
            file.puts "\" Generated By Rakefile"
            file.puts "source ~/vimfiles/os/win/vimrc"
    }
    puts "Download .gitconfig"
    http_download_uri URI.parse("https://raw.githubusercontent.com/timgifford/profile-settings/master/.gitconfig"), "../.gitconfig"
end 

def install_mac()
    FileUtils.cp 'vimrc', '../.vimrc'
    File.open('../.vimrc', 'a') { |file| 
            file.puts "\" Generated By Rakefile"
            file.puts "source ~/.vim/os/mac/vimrc"
    }
end

def http_download_uri(uri, filename)
  puts "Starting HTTP download for: " + uri.to_s
  http_object = Net::HTTP.new(uri.host, uri.port)
  http_object.use_ssl = true if uri.scheme == 'https'
  begin
    http_object.start do |http|
      request = Net::HTTP::Get.new uri.request_uri
      http.read_timeout = 500
      http.request request do |response|
        open filename, 'w' do |io|
          response.read_body do |chunk|
            io.write chunk
          end
        end
      end
    end
  rescue Exception => e
    puts "=> Exception: '#{e}'. Skipping download."
    return
  end
  puts "Stored download as " + filename + "."
end
